apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
spec:
  replicas: 5
  selector:
    app: myapp
  template:
    metadata:
      labels:
        app: myapp
        zone: prod
        version: v1
    spec:
        containers:
          - name: myapp-frontend
            image: hangyejiadao/frontend:v1
            ports:
              - containerPort: 80