---
- hosts: webservers
  vars:
    hello: Ansible
  tasks:
  - name: Add repo
    yum_repository:
         name: nginx
         description: nginx repo
         baseurl:  http://nginx.org/packages/centos/7/$basearch/
         gppcheck: no
         enabled: 1
  - name: Install nginx
    yum:
      name: nginx
      state: latest
  - name: Copy nginx configuration file
    copy:
      scr: ./site.conf
      dest: /etc/nginx/conf.d/site.conf
  - name: Start nginx
    service: 
      name: nginx
      state: started
  - name: Create wwwroot derectory
    file:
      dest: /var/www/html
      state: directory
  - name: Create test page index.html
    shell: echo "hello {{hello}}" >/var/www/html/index.html